name: Trigger auto deployment for container-app-d52r3n5zyjisk

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches:
      [ main ]
    paths:
    - 'server/**'
    - '.github/workflows/container-app-d52r3n5zyjisk-AutoDeployTrigger-ddbffee5-bf3d-4422-95c1-d5b7425c2423.yml'

  # Allow manual trigger
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPD52R3N5ZYJISK_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPD52R3N5ZYJISK_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPD52R3N5ZYJISK_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/server
          registryUrl:
          registryUsername: ${{ secrets.CONTAINERAPPD52R3N5ZYJISK_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPD52R3N5ZYJISK_REGISTRY_PASSWORD }}
          containerAppName: container-app-d52r3n5zyjisk
          resourceGroup: appspacesragapp929cadbd
          imageToBuild: default/container-app-d52r3n5zyjisk:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_
